//! Nextcloud Login Flow v2 — browser-based authentication.
//!
//! # Why Login Flow v2 and not username/password
//!
//! Two reasons:
//!
//! 1. **Users with 2FA can't just type their password** — they need an
//!    "app password" generated by Nextcloud. Login Flow v2 generates
//!    one automatically and hands it to us, so the user never deals
//!    with it manually.
//! 2. **The app password is revocable** — the user can kill Unkai's
//!    access from the Nextcloud security page without changing their
//!    real password. Storing a real password would make that impossible.
//!
//! # The protocol
//!
//! ```text
//!   client                                             server
//!     │                                                  │
//!     │ POST /index.php/login/v2                         │
//!     ├─────────────────────────────────────────────────►│
//!     │                                                  │
//!     │ 200 OK  { login: <url>, poll: {token, endpoint}} │
//!     │◄─────────────────────────────────────────────────┤
//!     │                                                  │
//!     │ (open `login` URL in browser, user authorises)   │
//!     │                                                  │
//!     │ POST <endpoint>   body: token=<token>            │
//!     ├─────────────────────────────────────────────────►│
//!     │ 404 "not yet"  — keep polling                    │
//!     │◄─────────────────────────────────────────────────┤
//!     │                                                  │
//!     │ POST <endpoint>   body: token=<token>            │
//!     ├─────────────────────────────────────────────────►│
//!     │ 200 { server, loginName, appPassword }           │
//!     │◄─────────────────────────────────────────────────┤
//! ```
//!
//! The polling contract is deliberately passive — the client decides how
//! often to poll. We don't poll in this crate; we hand the token and
//! endpoint to the caller (the Tauri command layer) and let it drive
//! polling on a timer the UI can control and cancel.

use serde::{Deserialize, Serialize};

use unkai_core::UnkaiError;
use unkai_core::models::TrustedCert;

use crate::client;

/// What the caller needs to open a browser window and later poll for
/// completion. The Tauri command returns this to the Svelte UI; the UI
/// opens `login_url`, then calls `poll_login` with `poll_token` /
/// `poll_endpoint` on a timer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoginFlowInit {
    /// URL to open in the system browser. Nextcloud renders the login
    /// and consent page there; on success it closes itself (in modern
    /// NC versions) or shows a "you can return to the app" message.
    pub login_url: String,
    /// Opaque token the server uses to correlate the poll with the
    /// browser session. Expires after ~20 minutes of inactivity.
    pub poll_token: String,
    /// Absolute URL the client should POST to while polling.
    pub poll_endpoint: String,
}

/// Returned from `poll_login` when the user has finished authorising.
///
/// Fields map 1:1 to the Nextcloud OCS response so renames or additions
/// server-side stay obvious.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoginFlowResult {
    /// The canonical server URL as NC sees it — can differ from what the
    /// user typed (e.g. if NC redirected https→https with a subpath).
    /// We store *this* one, not the user's input.
    pub server: String,
    /// NC login name — often differs from email. We display this to the
    /// user so they know which identity is connected.
    #[serde(rename = "loginName")]
    pub login_name: String,
    /// Revocable app password. Treat as equivalent to the real password
    /// for Basic auth purposes; must be stored in the OS keychain.
    #[serde(rename = "appPassword")]
    pub app_password: String,
}

// ── Raw wire format for the initial `login/v2` response ─────────

#[derive(Debug, Deserialize)]
struct RawLoginInit {
    login: String,
    poll: RawPoll,
}

#[derive(Debug, Deserialize)]
struct RawPoll {
    token: String,
    endpoint: String,
}

/// Kick off Login Flow v2 by POSTing to `{server}/index.php/login/v2`.
///
/// No credentials are sent; Nextcloud returns the browser URL + polling
/// handle regardless of whether the user exists yet.
pub async fn start_login(
    server_url: &str,
    trusted_certs: &[TrustedCert],
) -> Result<LoginFlowInit, UnkaiError> {
    let server = client::normalize_server_url(server_url);
    let url = format!("{server}/index.php/login/v2");
    tracing::info!("Starting Nextcloud Login Flow v2 against {server}");

    let http = client::build(trusted_certs)?;
    let resp = http
        .post(&url)
        .header("OCS-APIRequest", "true")
        .header("Accept", "application/json")
        .send()
        .await
        .map_err(|e| UnkaiError::Network(format!("login/v2 request failed: {e}")))?;

    if !resp.status().is_success() {
        return Err(UnkaiError::Nextcloud(format!(
            "login/v2 returned HTTP {}",
            resp.status()
        )));
    }

    let raw: RawLoginInit = resp
        .json()
        .await
        .map_err(|e| UnkaiError::Protocol(format!("login/v2 bad JSON: {e}")))?;

    Ok(LoginFlowInit {
        login_url: raw.login,
        poll_token: raw.poll.token,
        poll_endpoint: raw.poll.endpoint,
    })
}

/// Poll once to see whether the user has completed authorisation.
///
/// Return values:
/// - `Ok(Some(result))` — user approved; we have an app password.
/// - `Ok(None)` — not yet; caller should wait and poll again.
/// - `Err(...)` — a real failure (network down, server error). 404
///   specifically means "not yet" and is *not* surfaced as an error.
///
/// Poll cadence is the caller's choice. The official NC client polls
/// every second for up to 20 minutes; our UI uses 2s as a compromise
/// between responsiveness and not hammering the server.
pub async fn poll_login(
    poll_endpoint: &str,
    poll_token: &str,
    trusted_certs: &[TrustedCert],
) -> Result<Option<LoginFlowResult>, UnkaiError> {
    let http = client::build(trusted_certs)?;
    // Body is `token=<token>` as form data — not JSON. This is the one
    // place NC's API diverges from its usual JSON discipline.
    let resp = http
        .post(poll_endpoint)
        .header("OCS-APIRequest", "true")
        .header("Accept", "application/json")
        .form(&[("token", poll_token)])
        .send()
        .await
        .map_err(|e| UnkaiError::Network(format!("login/v2 poll failed: {e}")))?;

    let status = resp.status();
    if status == reqwest::StatusCode::NOT_FOUND {
        // Expected "not yet" — polling continues.
        return Ok(None);
    }
    if !status.is_success() {
        return Err(UnkaiError::Nextcloud(format!(
            "login/v2 poll returned HTTP {status}"
        )));
    }

    let result: LoginFlowResult = resp
        .json()
        .await
        .map_err(|e| UnkaiError::Protocol(format!("login/v2 poll bad JSON: {e}")))?;
    tracing::info!(
        "Nextcloud Login Flow v2 completed for user '{}' on '{}'",
        result.login_name,
        result.server
    );
    Ok(Some(result))
}
